package com.idunnololz.summit.reddit_objects

class CommentItemObject(
    kind: String,
    val data: RedditCommentItem?
) : RedditObject(kind)

class RedditCommentItem(
    val totalAwardsReceived: Int,
    val approvedAtUtc: Double?,
    val ups: Int,
    val awarders: List<String>,
    val modReasonBy: String?,
    val bannedBy: String?,
    val authorFlairType: String,
    val removalReason: String?,
    val linkId: String,
    val authorFlairTemplateId: String?,
    var likes: Boolean?,
    var replies: RedditObject?,
    val userReports: List<List<Any>>, // eg. [['spam',2],['trolling',1]]
    val saved: Boolean,
    val id: String,
    val bannedAtUtc: Double?,
    val modReasonTitle: String?,
    val gilded: Int,
    val archived: Boolean,
    val noFollow: Boolean,
    val author: String,
    val canModPost: Boolean,
    val sendReplies: Boolean,
    val parentId: String,
    val score: Int,
    val authorFullname: String,
    val reportReasons: Any?,
    val approvedBy: String?,
    val allAwardings: List<AwardInfo>,
    val subredditId: String,
    val body: String,
    val edited: Any, // Can be false or Double
    val authorFlairCssClass: String?,
    val isSubmitter: Boolean,
    val downs: Int,
    val authorFlairRichtext: Any?,
    val authorPatreonFlair: Boolean,
    val bodyHtml: String,
    val gildings: GildingInfo,
    val collapsedReason: Any?,
    val associatedAward: Any?,
    val stickied: Boolean,
    val authorPremium: Boolean,
    val subredditType: String,
    val canGild: Boolean,
    val subreddit: String,
    val authorFlairTextColor: String?,
    val scoreHidden: Boolean,
    val permalink: String,
    val numReports: Int?,
    val locked: Boolean,
    val name: String,
    val created: Double,
    val authorFlairText: String?,
    var collapsed: Boolean,
    val createdUtc: Double,
    val subredditNamePrefixed: String,
    val controversiality: Int,
    val depth: Int,
    val authorFlairBackgroundColor: String?,
    val modReports: Any?,
    val modNote: String?,
    val distinguished: Any?
)

/*

{
    "kind": "t1",
    "data": {
        "total_awards_received": 0,
        "approved_at_utc": null,
        "ups": 22,
        "awarders": [],
        "mod_reason_by": null,
        "banned_by": null,
        "author_flair_type": "text",
        "removal_reason": null,
        "link_id": "t3_f0z1i5",
        "author_flair_template_id": null,
        "likes": null,
        "replies": "",
        "user_reports": [],
        "saved": false,
        "id": "fh1apnp",
        "banned_at_utc": null,
        "mod_reason_title": null,
        "gilded": 0,
        "archived": false,
        "no_follow": false,
        "author": "_Trigglypuff_",
        "can_mod_post": false,
        "send_replies": true,
        "parent_id": "t3_f0z1i5",
        "score": 22,
        "author_fullname": "t2_xlmfr",
        "report_reasons": null,
        "approved_by": null,
        "all_awardings": [],
        "subreddit_id": "t5_3i60n",
        "body": "and then it just randomly spawns a whole part of the canon for mace windus character",
        "edited": false,
        "author_flair_css_class": null,
        "is_submitter": false,
        "downs": 0,
        "author_flair_richtext": [],
        "author_patreon_flair": false,
        "body_html": "&lt;div class=\"md\"&gt;&lt;p&gt;and then it just randomly spawns a whole part of the canon for mace windus character&lt;/p&gt;\n&lt;/div&gt;",
        "gildings": {},
        "collapsed_reason": null,
        "associated_award": null,
        "stickied": false,
        "author_premium": true,
        "subreddit_type": "public",
        "can_gild": true,
        "subreddit": "PrequelMemes",
        "author_flair_text_color": null,
        "score_hidden": false,
        "permalink": "/r/PrequelMemes/comments/f0z1i5/the_exact_moment_samuel_l_jackson_asked_george/fh1apnp/",
        "num_reports": null,
        "locked": false,
        "name": "t1_fh1apnp",
        "created": 1581241608.0,
        "author_flair_text": null,
        "collapsed": false,
        "created_utc": 1581212808.0,
        "subreddit_name_prefixed": "r/PrequelMemes",
        "controversiality": 0,
        "depth": 0,
        "author_flair_background_color": null,
        "collapsed_because_crowd_control": null,
        "mod_reports": [],
        "mod_note": null,
        "distinguished": null
    }
}

        */