name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'


jobs:
  test:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: touch sentry.properties
      - uses: musichin/ktlint-check@v3
        with:
          ktlint-version: '1.5.0'
          editorconfig: .editorconfig
          relative: true
